version: '3.0'

services:

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 21096:9100
  
  prometheus:
    image: lab-thay-linh:prometheus
    restart: always
    ports:
      - 9091:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  exporter: