version: '3.0'

services:

  node-exporter:
    image: prom/node-exporter:latest
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 21096:9100
  
  nvidia-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter
    restart: always
    environment:
      - DCGM_EXPORTER_NO_HOSTNAME=1
    cap_add:
      - SYS_ADMIN
    ports:
      - "9400:9400"
  
  app-tong-lb:
    build: nginx/
    restart: always
    network_mode: host
  
  prometheus:
    build: prometheus/
    restart: always
    ports:
      - 9091:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 10000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  exporter: